image: python:3.7-alpine

test:
  stage: test
  script:
  - apk add make
  - pip3 install -U sphinx  
  - pip3 install sphinx-rtd-theme
  - pip3 install sphinx-sitemap
  - pip3 install recommonmark
  - pip3 install sphinx_markdown_tables
  - cd docs
  - make html
  except:
  - master
  
pages:
  stage: deploy
  script:
  - apk add make
  - pip3 install -U sphinx  
  - pip3 install sphinx-rtd-theme
  - pip3 install sphinx-sitemap
  - pip3 install recommonmark
  - pip3 install sphinx_markdown_tables
  - cd docs
  - make html
  - cd ..
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master